# Generated by Django 3.2.3 on 2021-05-15 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_portfolio_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/%Y/%m/%d/')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio', to='projects.portfolio')),
            ],
        ),
    ]
