# Generated by Django 3.2.3 on 2021-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
