# Generated by Django 3.2.3 on 2021-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(default='', verbose_name='message'),
        ),
    ]
