# Generated by Django 3.2.2 on 2021-05-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_portfolio_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, help_text='recommended size 1000x665', null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='main image'),
        ),
    ]
