# Generated by Django 3.2.3 on 2021-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210514_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='author',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='show',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
